/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e225706;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class JankenTest {
    @Test void appHasAGreeting() {
        var board = new Gameboard();
        board.openStatus();
        board.janken();
    }
}
